### ISSUE TITLE
AnsiConsole class not found?  Can't compile or include.. fusesource..

### ISSUE THREAD

**Issue by gamesguru** [dialex/JCDP#12]
Tried building the source as well as grabbing the artifacts from MVNrepos.  Both have the same result.  Am I missing a reference or not structuring my project with meta-inf right?

This is the error I get when including the .jar:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jansi/AnsiConsole
	at com.diogonunes.jcdp.color.impl.WindowsColoredPrinter.println(WindowsColoredPrinter.java:197)
	at com.diogonunes.jcdp.color.ColoredPrinter.println(ColoredPrinter.java:225)
	at Program.main(Program.java:36)
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiConsole
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Process finished with exit code 1
```

When trying to compile the source

> import org._fusesource_.jansi.AnsiConsole;

```
Error:(9, 28) java: package org.fusesource.jansi does not exist
Error:(152, 20) java: package AnsiConsole does not exist
Error:(160, 20) java: package AnsiConsole does not exist
Error:(203, 24) java: package AnsiConsole does not exist
Error:(205, 20) java: package AnsiConsole does not exist
Error:(216, 24) java: package AnsiConsole does not exist
Error:(218, 20) java: package AnsiConsole does not exist
Error:(229, 24) java: package AnsiConsole does not exist
Error:(231, 20) java: package AnsiConsole does not exist
Error:(242, 24) java: package AnsiConsole does not exist
Error:(244, 20) java: package AnsiConsole does not exist
Error:(333, 20) java: package AnsiConsole does not exist
```

An immediate response would be appreciated as I am hoping to use this in a project that I am wrapping up soon.  Thanks for you work sir!

**Comment by dialex** [comment]
That is a dependency required in order for JCDP to support Windows' console. It is called JAnsi and it is still [available in Maven](https://mvnrepository.com/artifact/org.fusesource.jansi/jansi). If you want to compile from source, probably you will need to also add this dependency to your code.

The easiest/safest way to use JCDP is through a [Maven or Gradle](https://mvnrepository.com/artifact/com.diogonunes/JCDP/2.0.3.1) dependency.
Are you using one of these tools? Have you tried that?

Also what is your OS version + Java version?
