### ISSUE TITLE
How to print unicode ?

### ISSUE THREAD

**Issue by sgrillon14** [dialex/JCDP#13]
I try print unicode:

cp.print("  ███╗  ", Attribute.NONE, FColor.CYAN, BColor.BLACK);

but the result is: ???? (in cyan color)

My full sample [here](https://stackoverflow.com/questions/49303130/how-to-print-color-in-console-using-java-unix-mac-and-windows?noredirect=1#comment85612064_49303130)

note: unicode sqare is:
String unicodeMessage = "\u25A0";

**Comment by dialex** [comment]
<img width="796" alt="screen shot 2018-03-15 at 19 16 23" src="https://user-images.githubusercontent.com/2140450/37486124-70b40a5c-2885-11e8-8f3d-b59af6112ec4.png">

It works on my machine using the code below:

```java
        ColoredPrinter printer = new ColoredPrinter.Builder(1, false).build();

        printer.setForegroundColor(Ansi.FColor.GREEN);
        printer.println("It's working as you can see below:");
        printer.println("");

        printer.clear();
        printer.setBackgroundColor(Ansi.BColor.NONE);
        printer.setForegroundColor(Ansi.FColor.CYAN);
        printer.println(" ███████╗████████╗ █████╗  ██████╗██╗  ██╗ ██████╗ ██╗   ██╗███████╗██████╗ ███████╗██╗      ██████╗ ██╗    ██╗");
        printer.println(" ██╔════╝╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝██╔═══██╗██║   ██║██╔════╝██╔══██╗██╔════╝██║     ██╔═══██╗██║    ██║");
        printer.println(" ███████╗   ██║   ███████║██║     █████╔╝ ██║   ██║██║   ██║█████╗  ██████╔╝█████╗  ██║     ██║   ██║██║ █╗ ██║");
        printer.println(" ╚════██║   ██║   ██╔══██║██║     ██╔═██╗ ██║   ██║╚██╗ ██╔╝██╔══╝  ██╔══██╗██╔══╝  ██║     ██║   ██║██║███╗██║");
        printer.println(" ███████║   ██║   ██║  ██║╚██████╗██║  ██╗╚██████╔╝ ╚████╔╝ ███████╗██║  ██║██║     ███████╗╚██████╔╝╚███╔███╔╝");
        printer.println(" ╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ ╚═════╝   ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═╝     ╚══════╝ ╚═════╝  ╚══╝╚══╝ ");
        printer.clear();
```

Can you try to run the same code on yours? I used IntelliJ CE.

**Comment by sgrillon14** [comment]
I copy/paste your code and do not work on Maven + windows 7

![image](https://user-images.githubusercontent.com/5530550/37489814-1e62a36c-2899-11e8-9ed2-682c844e79f4.png)

on intelliJ i have the same problème:
![image](https://user-images.githubusercontent.com/5530550/37492039-104cee84-28a0-11e8-8a4d-2d93460e8080.png)
