### ISSUE TITLE
Fluent print syntax

### ISSUE THREAD

**Issue by bannmann** [dialex/JCDP#16]
Using `ColoredPrinter`, I always have to specify all three parameters (foreground, background, attributes) even when I want to change only one of them. This makes the calling code quite verbose.

Furthermore, when changing the colors inside a line, I see the following options:

1. use `System.out.println` with a string including several `generateCode(Ansi.Attribute, Ansi.FColor, Ansi.BColor)` calls (maybe stored as constants)
2. use several `ColoredPrinter.print(Object, Ansi.Attribute, Ansi.FColor, Ansi.BColor)` calls for the individual parts of the line

How about adding a fluent alternative, maybe something like the following (indendation for illustrative purposes)?

```java
fluentColoredPrinter
    .print("Hello, ")
    .push()
        .set(Ansi.FColor.BLUE)
        .set(Ansi.Attribute.BOLD)
        .print("World")
    .pop()
    .print("!")
    .println();
```

* New class `FluentColoredPrinter` (instantiated e.g. via `coloredPrinter.fluent()`) that delegates the real printing to `ColoredPrinter`.
* `push()` pushes a new state object to an internal stack
* `pop()` returns to the previous state
* `set()` has three overloads (one for `FColor`, `BColor` and `Attribute`) to make the method calls more compact. One could even go so far to add `(Attribute, FColor)`, `(Attribute, BColor)`,`(FColor, BColor)`,  and `(Attribute, FColor, BColor)` overrides.

If you're interested, I could write this and create a PR.

**Comment by nunofilipecosta** [comment]
hi @bannmann , go ahead, create the PR :) 🏅

**Comment by dialex** [comment]
Thanks for the suggestion @bannmann ! Help me understand it better, I'm thinking how I can fit your requirement to the library without looking like a _hack_. I would like to keep the API to a minimum.

> Using ColoredPrinter, I always have to specify all three parameters (foreground, background, attributes) even when I want to change only one of them.

When you create a ColoredPrinter, you pass to the builder the format you want to use by default for all its messages. You only have to pass the three params when you want to override that default. Does that happen so often?

```java
ColoredPrinter cp = new ColoredPrinter.Builder(1, false)
                        .foreground(FColor.WHITE).background(BColor.BLUE)   //setting format
                        .build();
cp.println("This message uses the format above");
cp.debugPrintln("So does this one");
```
I was expecting most of your prints would look like that. Can you share a code snippet where this gets verbose?

-----

**Alternative 1**: Have you considered having multiple printers with different default formats?

```java
ColoredPrinter cpWhiteOnBlue = new ColoredPrinter.Builder(1, false).foreground(FColor.WHITE).background(BColor.BLUE).build();
ColoredPrinter cpRedOnYellow = new ColoredPrinter.Builder(1, false).foreground(FColor.RED).background(BColor.YELLOW).build();

cpWhiteOnBlue.print("It starts with blue bkg...");
cpRedOnYellow.println(" and then changes to yellow");
```

**Alternative 2**: What if we created an `Ansi.Format` object that would encapsulate the three params? That way you can create your formats once and then use them in your code. It's less verbose.

```java
AnsiFormat fWhiteOnBlue = new AnsiFormat(Attribute.BOLD, FColor.WHITE, BColor.BLUE);
AnsiFormat fRedOnYellow = new AnsiFormat(Attribute.None, FColor.RED, BColor.YELLOW);

ColoredPrinter cp = new ColoredPrinter.Builder(0, false).build();

cp.print("It starts with blue bkg...", fWhiteOnBlue);
cp.println(" and then changes to yellow", fRedOnYellow);
```

Check if one of these quick-fixes meets your needs. If not, we'll talk again about the fluent printer API ;)

**Comment by dialex** [comment]
It's been several months without any update, so I'm closing this issue.
