### ISSUE TITLE
cmd cant output colorful messages.

### ISSUE THREAD

**Issue by MikiraSora** [dialex/JCDP#5]
![w 1 _jqn53j5yu25wv z4f](https://cloud.githubusercontent.com/assets/7549173/20555358/a07f2fca-b19c-11e6-9014-745be485f7a4.jpg)
windows 10.

**Comment by dialex** [comment]
Sorry for the late reply, I did not get a notification -- it won't happen again 😉

From what I see from the screenshot, on PowerShell it displays color correctly but not on Command Line, right? It should work, as I have a working screenshot from Windows 8.1 cmd.

It looks like cmd is not processing the ANSI codes and formatting the font. Please try this: https://web.liferay.com/web/igor.spasic/blog/-/blogs/enable-ansi-colors-in-windows-command-prompt

Copy below for reference:

-----

- Download from http://adoxa.110mb.com/ansicon/index.html or https://github.com/adoxa/ansicon
- Extract proper files, depending on your windows os: 32bit or 64bit
- Install it with: ansicon -i

Thats all. From now on, your windows command lines will be aware of ansi colors.
