### ISSUE TITLE
BACK_COLOR for True colors doesn't seem to work when I try with 5.0.0

### ISSUE THREAD

**Issue by fizaan** [dialex/JCDP#53]
**Describe the bug**
BACK_COLOR doesn't seem to work when I tried for True Colours RGB.

**To Reproduce**
See screenshot

**Expected behavior**
BACK_COLOR should display correctly.

<img width="613" alt="Code" src="https://user-images.githubusercontent.com/27024481/98878795-e05bde00-2451-11eb-98fa-b348e8e5b853.PNG">
<img width="415" alt="consoleOut" src="https://user-images.githubusercontent.com/27024481/98878804-e3ef6500-2451-11eb-84ab-017ab3843e34.PNG">

**Screenshots**

**Environment**
 Windows 10 using JColor version 5.0.0. Java Version 13.0

**Comment by dialex** [comment]
Thanks for reporting it. I have limited time now, but I soon as I have a break I'll try to reproduce it.

**Comment by fizaan** [comment]
No problem! Take your time 👍

**Comment by dialex** [comment]
Thank you for waiting. I tried to reproduce your issue using the code you showed in your screenshot:

```java
        Thread.currentThread();
        Random _rand = new Random();

        System.out.println(colorize("This text will be yellow on red", BRIGHT_YELLOW_TEXT(), RED_BACK()));
        System.out.println("\n");

        System.out.println("Use Case 7 - Any TrueColor (RGB), as long as your terminal supports it:");
        for (int i = 0; i < 5; i++) {
            Attribute bgCol = BACK_COLOR(
                    _rand.nextInt(255), _rand.nextInt(255), _rand.nextInt(255));
            System.out.println(colorize("Test: " + i, bgCol));
        }
        System.out.println("\n");
```

Your code is actually very similar to "use case 7" of my documentation, so it's a scenario I tested before releasing the TrueColors feature.

I ran it inside IntelliJ CE and as you can see from my screenshot, the terminal displayed the background with TrueColor (8-bit) colours.

![Screenshot 2020-11-29 at 19 48 45](https://user-images.githubusercontent.com/2140450/100551957-ee946180-327b-11eb-9769-5ce643ee7a41.png)

Mind that for TrueColors to be displayed your terminal needs to support it. Which terminal did you use?

I'm not sure if Windows Command Prompt (cmd.exe) supports TrueColors. I saw this [update](https://devblogs.microsoft.com/commandline/24-bit-color-in-the-windows-console/) but it's about "Windows Console". When they say "Console" are they referring to "Windows Command Prompt" or their new shiny "Windows Terminal"? 🤷‍♂️

Can you please try to run your code on PowerShell? Or [Windows Terminal](https://github.com/microsoft/terminal)?

**Comment by fizaan** [comment]
Hi! 

Yes I ran the code on Windows cmd console as well as the power shell console window and the background was not getting highlighted in both cases. Maybe this is a windows limitation as you pointed out. Unfortunately I want to run my code on the console only for now (as opposed to some IDE console like eclipse or IntelliJ so. Thanks for your support!

**Comment by dialex** [comment]
Oh bummer 😞 

Before we give up, let's try one to figure out what's the cause of the issue:
- What is the Windows 10 build you're using?
- From your output screenshot format, I assume you are running your app with Maven. Could you try generate a jar of your app, and then use `java` to run it directly (without `mvn`)?
- Just for sanity sake, could you import your code to an IDE (i.e. IntelliJ), run your code there and check the IDE's terminal output?

**Comment by fizaan** [comment]
Here some more output:

1) dos command line
![image](https://user-images.githubusercontent.com/27024481/100658774-9615a080-331d-11eb-8d4b-47e136e2e644.png)

2) power shell:
![image](https://user-images.githubusercontent.com/27024481/100658883-bfcec780-331d-11eb-9215-651a3ab6cf77.png)

3) Eclipse IDE (cannot run from IDE as it required some parameters to be set in the environment which I am too lazy to do right now. I can do it later if necessary. Thanks!

**Comment by dialex** [comment]
1. I checked your Windows 10 build and `14393` is fairly old, from 2016. I'm running `19041`, from 2020. Not sure that makes any difference, and it would be a big change for you, so let's ignore that.
2. Even PowerShell fails to show color... so it's unlikely a Windows issue. The remaining suspects are Maven and JColor.
3. Yes, please try it but take your time.
