### ISSUE TITLE
First word not printed properly

### ISSUE THREAD

**Issue by manticore-projects** [dialex/JCDP#55]
Dear developers, I love this lib but I face a small challenge
```java
private static final AnsiFormat KEYWORD_FORMAT = new AnsiFormat(BLUE_TEXT(),  BOLD());

private static final void appendKeyWord(
      StringBuilder builder, OutputFormat format, String keyword, String before, String after) {
    switch (format) {
      case PLAIN:
        builder.append(before).append(keyword).append(after);
        break;
      case ANSI:
        builder.append(before).append(KEYWORD_FORMAT.format(keyword)).append(after);
        break;
      default:
        builder.append(before).append(keyword).append(after);
        break;
    }
  }

appendKeyWord(builder, outputFormat, "DELETE", "", " ");
```

Produces output like this
<pre><font color="#55FF55">are</font>@ryzen <font color="#00AA00">~/d/s/jsqlformatter</font> (main) <font color="#AA0000">[</font><font color="#FF5555"><b>1</b></font><font color="#AA0000">]</font>&gt; <font color="#005FD7">/usr/lib/jvm/java-11-graalvm/bin/java</font> <font color="#00AFFF">-jar</font> <font color="#00AFFF"><u style="text-decoration-style:single">dist/JSQLFormatter.jar</u></font> <font color="#999900">&quot;DELETE FROM a where b=&apos;c&apos;;&quot;</font>
[34;47;1m DELETE <span style="background-color:#AAAAAA"><font color="#5555FF"><b>FROM</b></font></span> a
<span style="background-color:#AAAAAA"><font color="#5555FF"><b>WHERE</b></font></span> b = &apos;c&apos;
;</pre>

![image](https://user-images.githubusercontent.com/18080123/114861045-f281e400-9e16-11eb-8f3f-6b2243d44eef.png)

![image](https://user-images.githubusercontent.com/18080123/114861103-062d4a80-9e17-11eb-868d-709f366ba1ec.png)

The first Word is distorted and I do not know why.

**Comment by manticore-projects** [comment]
Nevermind, I trimmed the returning string (e.g. ```String.trim()```).
Without the trim, everything works as expected.

**Comment by dialex** [comment]
Good to know you found a solution (and that you find this library useful) 😃
