### ISSUE TITLE
Import in java program

### ISSUE THREAD

**Issue by gruvw** [dialex/JCDP#58]
Hello, I can't seem to find an easy import to display your README example...

With `import com.diogonunes.jcolor.Ansi;`, I am forced to use `Ansi.colorize()` and in your example you are using `colorize()` directly (same for `Attribute.YELLOW_TEXT()` and `YELLOW_TEXT()`).

Are you using this ?
```java
import com.diogonunes.jcolor.Attribute;
import com.diogonunes.jcolor.AnsiFormat;
import static com.diogonunes.jcolor.Ansi.*;
import static com.diogonunes.jcolor.Attribute.*;
```
or is there a simpler way ?

**Comment by dialex** [comment]
Hey! The example you see in the README is fully working in this file https://github.com/dialex/JColor/blob/19b943a6f47d25fcb9763d5f6f00983a1c7fb59d/src/test/java/com/diogonunes/jcolor/tests/acceptance/TestHumanEye.java#L7 I've highlighted the import that you need.

Does that solve your issue?

**Comment by gruvw** [comment]
Yes thank you 👌
