### ISSUE TITLE
README.md code samples are confusing

### ISSUE THREAD

**Issue by Macintosh-Fan** [dialex/JCDP#63]
Hello. Just reading over the `README.md` file, and there is one issue: where do the static imports come from?

Like, where is the colorize method (`colorize("   ", bkgColor)`) from?
Same thing for `BACK_COLOR(randomInt(255), randomInt(255), randomInt(255))`.

**Comment by dialex** [comment]
Hey. I'm sorry it wasn't clear to your.
I was hoping that your IDE would suggest the imports after you copied those lines to your workspace.

You can have a look at the full code of that [example here](https://github.com/dialex/JColor/blob/main/src/test/java/com/diogonunes/jcolor/tests/acceptance/TestHumanEye.java). The imports are

```java
import static com.diogonunes.jcolor.Ansi.colorize;
import static com.diogonunes.jcolor.Attribute.*;
```
