### ISSUE TITLE
Doesn't work on command prompt

### ISSUE THREAD

**Issue by jredfox** [dialex/JCDP#69]
**Describe the bug**
the printlines do not show color when running the program from a compiled jar via command prompt. `java -jar jcolor.jar` it printlines the escape characters but not the color

I noticed calling echo with an ansi escape sequence seems to fix this. If the terminal is command prompt you should apply a fix similar to this
`new ProcessBuilder(new String[]{"cmd", "/c", "echo", "\u001B[42m A TEST[0m"}).inheritIO().start().waitFor();`

**Comment by dialex** [comment]
Windows Command Prompt does not support ANSI escape codes by default. Check [these workarounds](https://github.com/dialex/JColor#troubleshoot).

**Comment by jredfox** [comment]
If you actually read my issue I have a fix for it without screwing up admin privileges and reg editing the os which can break things

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dialex** [comment]
The link I shared has 4 workarounds, only one requires reg editing. I would like to avoid a 5th workaround.
Also, does your fix work for Windows, Linux and Mac? I don't want to go back to `if (OS == WIN) then X else Y` logic.
