### ISSUE TITLE
Cygwin not showing colors but has ANSI support

### ISSUE THREAD

**Issue by ahasbini** [dialex/JCDP#7]
I've tested the library with Cygwin on Windows 10. It did not show the colors of the text however Cygwin has ANSI support.

Here is an example code to try out and replicate the issue:
```
ColoredPrinter coloredPrinter = new ColoredPrinter.Builder(1, false).build();

coloredPrinter.println("test", Attribute.NONE, FColor.CYAN, BColor.NONE);

System.out.println("\u001B[31m" + "TEST" + "\u001B[0m");

coloredPrinter.print("test scan:", Attribute.NONE, FColor.RED, BColor.NONE);
System.out.print("\u001B[35m");
Scanner scan = new Scanner(System.in);
scan.nextLine();
System.out.println("\u001B[0m");

coloredPrinter.clear();
```

[Link to the ANSI codes can be found here](http://stackoverflow.com/questions/5762491/how-to-print-color-in-console-using-system-out-println)

**Comment by dialex** [comment]
Sorry for the late reply, I did not get a notification -- it won't happen again 😉

Thanks for the ANSI codes link. I followed that answer and started using the JANSI lib for windows compatibility. So I'm assuming the issue might be on that lib.

I've upgraded the version used to the latest JANSI version available. I'll push the update to nexus on JCDP v2.0.2 and ask you to try again.

**Comment by dialex** [comment]
New tag published on [GitHub](https://github.com/dialex/JCDP/releases/tag/v2.0.2) and still pending on [Maven](https://mvnrepository.com/artifact/com.diogonunes/JCDP/2.0.2)
