### ISSUE TITLE
ColoredPrinter println which takes msg, attribute, fg and bg parameters is not putting new line

### ISSUE THREAD

**Issue by rajpra8** [dialex/JCDP#9]
ColoredPrinter println(Object msg, Attribute attr, FColor fg, BColor bg) api is calling  getImpl().print rather than getImpl().println.
 
/src/main/java/com/diogonunes/jcdp/color/ColoredPrinter.java#L345

    @Override
    public void println(Object msg, Attribute attr, FColor fg, BColor bg) {
        getImpl().print(msg, attr, fg, bg);
    }

**Comment by dialex** [comment]
This was fixed by the commit above. Cheers @Flawedspirit

**Comment by dialex** [comment]
New tag published on [GitHub](https://github.com/dialex/JCDP/releases/tag/v2.0.2) and still pending on [Maven](https://mvnrepository.com/artifact/com.diogonunes/JCDP/2.0.2)
